### ISSUE TITLE
parseFromB64 crash as atob function is not referenced

### ISSUE THREAD

**Issue by eyahalomi** [Comcast/scte35-js#53]
Using version 0.2.11
        const bytes = Uint8Array.from(atob(b64).split("").map((c) => c.charCodeAt(0)));
atob need to be "required" and added to package.json dependencies.

**Comment by avhetman** [comment]
Hello @eyahalomi, it looks like atob is currently shimmed here: https://github.com/Comcast/scte35-js/blob/master/util/dom-shim.js#L19

We may not actually need atob at all, since we technically only need it to parse the b64 string, which is just:
`(b64) => return (new Buffer(b64, 'base64')).toString('binary')`

Could you please provide more information regarding your use case so that we can properly ascertain the best way to enhance this library to meet your needs?

**Comment by eyahalomi** [comment]
Hi Andrie,
I am fine with your implementation.
With Node when you create new instance of SCTE35 class and invoke
inst.parseFromB64() it will throw exception atob is not included. Can we
import that function from dom-shim into scte35.js so that function can run?
Thanks,
Eran

**Comment by avhetman** [comment]
Understood, let me make some changes and make a PR. I will have an update shortly.

**Comment by avhetman** [comment]
@eyahalomi this should now be resolved as of the latest version 0.2.12
Also, I really appreciate you using this tool and making enhancement requests and bug reports! Thanks so much Eran

**Comment by eyahalomi** [comment]
Thank you! You are doing a great job and we enjoy the benefit.
